services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vk_analysis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5432:5432"